Scrollbar: Add more error details if data('scrollbars') is not set
The error log shows that $parent.data('scrollbars') may be undefined in
some rare cases. Because we do not know how this can happen, better
error details have been added.

Error: Cannot read property 'forEach' of undefined

Also removed unused code in BenchColumn and SimpleTabBox.

205172