PlaceholderException: add expectation for null-value
Change-Id: Ie03d7448a3095e6a53fa60afca10fab00e8a9966
(cherry picked from commit 0a47f1b39cbcbc380b2d4f10ae0feccc4ad0ae98)
Reviewed-on: https://git.eclipse.org/r/134132
Tested-by: CI Bot
Reviewed-by: Andi Bur <andi.bur@gmail.com>