Temporary revert FilterField css because of minimizer incompatibilities
Some css rules of the filter field cannot be processed by the
css-minimizer plugin. It produces errors like:

DataCloneError: function yyGetSharedState() { return sharedState_yy; }
could not be cloned.