TableUiPreferences: ignore non-displayable columns
Columns with displayable=false are never visible to the user. Therefore,
it is unnecessary to store any information about these columns in the
ui preferences. They are neither relevant nor can they be changed. To
make things more deterministic, non-displayable columns are always
placed at the beginning of the 'columns' array when preferences are
applied.

Exception: in the initial ui preferences of a table, we deliberately
include non-displayable columns to be able to restore the initial state
exactly when the user invokes the 'restore to factory settings' menu.