Load tests with apache http may yield NoHttpResponseException
When doing load tests with scout and apache client as
DefaultHttpTransportManager, after some requests an exception occurs.

org.apache.http.NoHttpResponseException: localhost:8180 failed to
respond
org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
...

The cause is that ApacheHttpTransportFactory is returning true in the
keepAlive callback.

Fixed by using apache http defaults that check for
Connection: close
and
Connection: Keep-Alive
(241753)

Change-Id: Ifec4bf09c8d55916fc70202d40be6c02a6de0103
Signed-off-by: Ivan Motsch <ivan.motsch@bsiag.com>
Reviewed-on: https://git.eclipse.org/r/138093
Tested-by: CI Bot