use Interface ConcurrentMap as variable type
The signature of ConcurrentHashMap.keySet() changed in JAVA 8. So even
if compiled with target 1.7 the resulting bytecode will not run on 
JAVA 7: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;

ByteCode with ConcurrentHashMap:
invokevirtual #4                  // Method java/util/concurrent/ConcurrentHashMap.keySet:()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;

ByteCode with ConcurrentMap:
invokeinterface #4,  1            // InterfaceMethod java/util/concurrent/ConcurrentMap.keySet:()Ljava/util/Set;

Change-Id: I9ea47e838d145e7c8ef54cad45d7d9ccf6079768
Reviewed-on: https://git.eclipse.org/r/62307
Reviewed-by: Patrick Bänziger <patrick.baenziger@bsi-software.com>
Reviewed-by: Stephan Leicht Vogt <stephan.leichtvogt@bsi-software.com>
Tested-by: Stephan Leicht Vogt <stephan.leichtvogt@bsi-software.com>