TableFooter: prevent error when navigating away while footer is opening
When animation is complete, a callback function is called that is
responsible for displaying the status tooltip (_showTableStatusTooltip).
Because the callback is run asynchronously, a check if the footer is
still rendered has to be added. Otherwise, a T6 error might occur:

TypeError: Cannot read property 'length' of null
    at Tooltip.entryPoint
    at Tooltip.render
    at TableFooter._showTableStatusTooltip
    at TableFooter.<anonymous>
    at HTMLDivElement.complete
    ...

Can be reproduced when a page with "search required" is clicked the
first time. While the footer form is still opening (!), click on any
other page.

Change-Id: I2408ae8d21bad6a5bc75eee5ec35b48f62ee9464