Bug 458143 - Enable Scout for pure Java applications (without osgi) https://bugs.eclipse.org/bugs/show_bug.cgi?id=458143
Fix 'NoClassDefFoundError' problem of ScoutTexts because of service call
in static initializer.

Change-Id: I0e759bfc10b3e8e39be9e6b39722fb5e2536a491
Reviewed-on: https://git.eclipse.org/r/42943
Reviewed-by: Daniel Wiehl <daniel.wiehl@bsiag.com>
Tested-by: Daniel Wiehl <daniel.wiehl@bsiag.com>