ESLint: remove disabled rules
Disabled rules that are not part of the recommended eslint config don't
need to be listed because they are not active anyway.

Exception: prefer-const is enabled by the recommended config of
typescript-eslint.